REM   Script: Create Table Statements
REM   Create Table

DROP TABLE Bill                 CASCADE CONSTRAINTS;

DROP TABLE Customers            CASCADE CONSTRAINTS;

DROP TABLE Employee             CASCADE CONSTRAINTS;

DROP TABLE Project_P            CASCADE CONSTRAINTS;

DROP TABLE Project_Manager      CASCADE CONSTRAINTS;

DROP TABLE Project_Schedule     CASCADE CONSTRAINTS;

DROP TABLE Skills               CASCADE CONSTRAINTS;

DROP TABLE Task                 CASCADE CONSTRAINTS;

DROP TABLE Work_Log             CASCADE CONSTRAINTS;

CREATE TABLE Bill 
(BILL_NO		NUMBER(3), 
 HoursWorkd		NUMBER(3), 
 CONSTRAINT Bill_BILL_NO_PK PRIMARY KEY (BILL_NO) ) ;

CREATE TABLE Customers 
  (CUSTOMER_ID		NUMBER(6), 
   NAME 			VARCHAR2(50), 
   PHONE_NO			NUMBER(10), 
   CUSTOMER_REGION	VARCHAR2(2), 
   CONSTRAINT Customers_CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID)	) ;

CREATE TABLE Employee 
(EMP_ID			NUMBER(6), 
 LNAME			VARCHAR2(30), 
 FNAME			VARCHAR2(30), 
 MID_INITIAL	VARCHAR2(1), 
 EMP_REGION		VARCHAR2(2), 
 DATE_HIRED		DATE, 
 CONSTRAINT Employee_EMP_ID_PK PRIMARY KEY (EMP_ID)	) ;

CREATE TABLE Project_Manager 
    (PMEMP_ID			NUMBER(6), 
     LNAME			VARCHAR2(30), 
     FNAME			VARCHAR2(30), 
     CONSTRAINT Project_Manager_EMP_ID_PK PRIMARY KEY (PMEMP_ID), 
     CONSTRAINT Project_Manager_EMP_ID_FK FOREIGN KEY (PMEMP_ID) REFERENCES EMPLOYEE (EMP_ID)	) ;

CREATE TABLE Project_P 
   (PROJECT_ID		NUMBER(4), 
    PCUSTOMER_ID		NUMBER(6), 
    PEMP_ID			NUMBER(6), 
    P_DESCRIPTION	VARCHAR2(50), 
    CONTRACT_DATE	DATE, 
    EST_StartDate	DATE, 
    EST_EndDate	DATE, 
    ESTBUDGET		NUMBER(7), 
    StartDate		DATE, 
    EndDate			DATE, 
    COST			NUMBER(7), 
    CONSTRAINT Project_PROJECT_ID_PK PRIMARY KEY (PROJECT_ID), 
    CONSTRAINT Project_CUSTOMER_ID_FK FOREIGN KEY (PCUSTOMER_ID) REFERENCES Customers (CUSTOMER_ID), 
    CONSTRAINT Project_EMP_ID_FK FOREIGN KEY (PEMP_ID) REFERENCES Project_Manager (PMEMP_ID)	) ;

CREATE TABLE Project_Schedule 
      (ASSIGNMENT_ID	NUMBER(4), 
       PSEMP_ID			NUMBER(6), 
       PSPROJECT_ID       NUMBER(4), 
       PROJECT_TASK		VARCHAR2(50), 
       ASSGN_StartDate	DATE, 
       ASSGN_EndDate	DATE, 
       CONSTRAINT Project_Schedule_EMP_ID_FK FOREIGN KEY (PSEMP_ID) REFERENCES Employee (EMP_ID), 
       CONSTRAINT Project_Schedule_PROJECT_ID_FK FOREIGN KEY (PSPROJECT_ID) REFERENCES Project_P (PROJECT_ID)  ) ;

CREATE TABLE Skills 
 (SKILL_ID		VARCHAR2(10), 
  SEMP_ID		NUMBER(6), 
  S_DESCRIPTION	VARCHAR2(50), 
  RATE_OF_PAY	NUMBER(4), 
  CONSTRAINT Skills_SKILL_ID_PK PRIMARY KEY (SKILL_ID), 
  CONSTRAINT Skills_EMP_ID_FK FOREIGN KEY (SEMP_ID) REFERENCES Employee (EMP_ID)	) ;

CREATE TABLE Task 
     (TASK_ID 		NUMBER(7), 
      T_DESCRIPTION	VARCHAR2(50), 
      SKILLS_REQ	VARCHAR2(30), 
      NO_OF_EMP		NUMBER(1), 
      StartDate		DATE, 
      EndDate		DATE, 
      CONSTRAINT Task_TASK_ID_PK PRIMARY KEY (TASK_ID)  ) ;

CREATE TABLE Work_Log 
(ASSIGNMENT_ID	NUMBER(4), 
 WeekEnding		DATE, 
 HoursWorked	NUMBER(3), 
 BILL_NO		NUMBER(3), 
 EMP_NAME       VARCHAR2(50), 
 CONSTRAINT Work_Log_BILL_NO_FK	FOREIGN KEY (BILL_NO) REFERENCES Bill (BILL_NO)	) ;

