REM   Script: TRIGGER Statements
REM   TRIGGER

CREATE TABLE N_Customer ( 
      audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
      table_name       VARCHAR2(255), 
      transaction_name VARCHAR2(10), 
      by_user          VARCHAR2(30), 
      transaction_date DATE 
);

CREATE OR REPLACE TRIGGER customers_audit_trg 
    AFTER  
    UPDATE OR DELETE  
    ON customers 
    FOR EACH ROW     
DECLARE 
   l_transaction VARCHAR2(10); 
BEGIN 
   
   l_transaction := CASE   
         WHEN UPDATING THEN 'UPDATE' 
         WHEN DELETING THEN 'DELETE' 
   END; 
 
      
   INSERT INTO N_Customer (table_name, transaction_name, by_user, transaction_date) 
   VALUES('CUSTOMERS', l_transaction, USER, SYSDATE); 
END; 
/

